### ISSUE TITLE
Recuperação de contas pelo email

### ISSUE THREAD

**Issue by MrPowerGamerBR** [PerfectDreams/DreamAuth#2]
### Registrar email
Após estar logado, `/email EndereçoDoEmail` irá associar a conta do usuário com o email determinado.

Na database, o email será salvado no valor `email` dentro do objeto `auth`, associado ao usuário na collection `users`

### Recuperação de contas
Ao usar `/recuperar EndereçoDoEmail`, caso o email seja o mesmo que o enviado anteriormente pelo usuário, será enviado um email pelo Mailgun contendo o link para recuperar a senha (junto com um token único na URL)

Ao iniciar a recuperação, o token junto com o tempo em que ele foi gerado deverá ser salvo no valor `email` dentro do objeto `auth`, associado ao usuário na collection `users`

**Comment by MrPowerGamerBR** [comment]
@BsouzaM enquanto é algo interessante, existe o problema de pessoas maliciosas que sabem o email registrado em uma conta entrarem apenas para pedir para recuperar a conta para bloquear a conta.

Por exemplo, o Steve registrou o email `steve@perfectdreams.net` na conta dele, e a Alex sabe que ele registrou este email porque ela encontrou o email dele na seção de contato empresarial no canal do YouTube dele, ai ela entra na conta apenas para bloquear a conta dele usando `/recuperar steve@perfectdreams.net`.

Como emails são públicos, não daria certo fazer isto... só se colocasse outra senha única para recuperar, mas se o usuário já não lembra a senha da conta dele, lembrar a senha para recuperar o email vai sre mais difícil ainda!

**Comment by BsouzaM** [comment]
> Por exemplo, o Steve registrou o email steve@perfectdreams.net na conta dele, e a Alex sabe que ele registrou este email porque ela encontrou o email dele na seção de contato empresarial no canal do YouTube dele, ai ela entra na conta apenas para bloquear a conta dele usando /recuperar steve@perfectdreams.net.

E não seria melhor adicionar um autenticador para saber que Steve é o dono da conta e não Alex?

**Comment by MrPowerGamerBR** [comment]
@BsouzaM aí teria que implementar um sistema de two factor authentication, né?

**Comment by BsouzaM** [comment]
Sim
